name = "cf-fire-430a" # todo

main = "toGopp.js"
compatibility_date = "2024-08-30"
send_metrics = false

[vars]
# 配置全局加密变量 需要再控制面板中设置全局变量，再此文件设置为明文全局变量
P6DD = "ipv6.google.com.hk"
P4DD = "www.google.com.hk"
MMDD = "www.google.com.hk"

VDST = "请配置worker自定义域名"


